// Mwuah — daily couple questions. Same one shows for both of you each day.
export const QUESTIONS = [
  'What’s your favourite memory of us so far?',
  'What first made you fall for me?',
  'Where do you most want to travel together?',
  'What’s a tiny thing I do that you love?',
  'What does your perfect lazy Sunday with me look like?',
  'What song reminds you of us?',
  'What’s something new you’d love us to try together?',
  'When did you feel most loved by me?',
  'What’s your favourite thing about our relationship?',
  'If we could relive one day together, which one?',
  'What’s a little dream you have for our future?',
  'What’s the cutest thing I’ve ever said to you?',
  'What makes you feel safe with me?',
  'What’s a date you’d love to go on this month?',
  'What’s something you’re grateful for about me today?',
  'What’s our funniest moment together?',
  'How would you describe us in three words?',
  'What’s a habit of mine that makes you smile?',
  'What food will always remind you of me?',
  'What’s your favourite way I show you love?',
  'What’s something you want us to get better at together?',
  'What’s the best gift I’ve ever given you (big or small)?',
  'Where do you picture us in five years?',
  'What’s a movie you’d happily rewatch with me?',
  'What’s a small adventure we should have soon?',
  'What did you think when we first met?',
  'What’s your favourite photo of us and why?',
  'What’s one thing you’d never change about us?',
  'What makes you laugh the most about me?',
  'What’s a tradition you’d love us to start?',
  'What’s something kind I did that you still remember?',
  'What’s your idea of a perfect morning together?',
  'What do you love most about how we argue and make up?',
  'What’s a place that feels like “ours”?',
  'What’s a goal you’d love us to reach as a team?',
  'What’s the most romantic thing you can imagine us doing?',
  'What’s your favourite inside joke we share?',
  'When are you most excited to see me?',
  'What’s something about me you’re proud of?',
  'What would your perfect anniversary with me be?',
  'What’s a flaw of mine you’ve grown to adore?',
  'What’s the first thing you want to do when we’re together next?',
  'What does “home” mean to you when you think of us?',
  'What’s a tiny promise you want to make me today?',
  'What colour, taste, or smell reminds you of me?',
  'What’s your favourite season to spend with me and why?',
  'What’s something I taught you without realising?',
  'What’s a comfort show or book you’d share with me?',
  'What’s the kindest thing I could do for you this week?',
  'What’s your favourite version of me — sleepy, silly, serious?',
  'What’s one wish you have for us this year?',
  'What’s a memory you hope we make this month?',
  'What’s something that always makes you think of me?',
  'How do you feel right now, in this exact moment, about us?',
];

// Deterministic question for a given 'YYYY-MM-DD' — both of you see the same one.
export function questionForDay(dayStr) {
  const [y, m, d] = String(dayStr).split('-').map(Number);
  const dayNum = Math.floor(Date.UTC(y, (m || 1) - 1, d || 1) / 86400000);
  const i = ((dayNum % QUESTIONS.length) + QUESTIONS.length) % QUESTIONS.length;
  return QUESTIONS[i];
}
